(set-register ?0 '(file . "~/.emacs"))
(set-register ?1 '(file . "/cygdrive/c/Users/nealm/notes.org"))
(set-register ?2 '(file . "/cygdrive/c/Users/nealm/todo.org"))

(require 'package)
(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")
	("org" . "http://orgmode.org/elpa/")
;	("marmalade" . "http://marmalade-repo.org/packages/")
	("melpa" . "http://melpa.milkbox.net/packages/")
	))
(package-initialize)

(add-to-list 'load-path "~/.emacs.d/snippets")
(add-to-list 'exec-path "/cygdrive/c/cygwin64/bin")
(load "~/.emacs.d/misc-settings.el")
(require 'yasnippet)
(require 'switch-window)
(require 'multiple-cursors)
(require 'helm)
(require 'auto-complete)
(require 'chess-stockfish)
(require 'chef-mode)
(require 'epresent)
(load "~/.emacs.d/misc-functions.el")
(load "~/.emacs.d/keybindings.el")
(load "~/.emacs.d/languages.el")
(load-theme 'zenburn 1)
