(mapc (function (lambda (binding) (global-set-key (kbd (car binding)) (cadr binding))))
      '(
	 ("<C-wheel-up>" (lambda () (interactive) (text-scale-increase 1)))
	 ("<C-wheel-down>" (lambda () (interactive) (text-scale-decrease 1)))
	 ("<f1>" man)
	 ("<f5>" revert-buffer)
	 ("C-c C-f" compile)
	 ("C-c a" org-agenda)
	 ("C-c b" org-iswitchb)
	 ("C-c c" org-capture)
	 ("C-c l" org-store-link)
	 ("C-c v" vc-compare-with-recent-(vector )ersion)
	 ("C-c j" json-format)
	 ("C-c <left>" winner-undo)
	 ("C-c <right>" winner-redo)	 
	 ("C-x M-SPC" delete-blank-lines)
	 ("C-x w w" hilight-thing-at-point)
	 ("M-g" goto-line)
	 ("M-m" iy-go-to-char)
	 ("M-x" helm-M-x)
	 ("C-|" toggle-frame-split)
	 ("M-s" jump-char-forward)
	 ("M-S-s" jump-char-backward)
	 ("C-x k" kill-this-buffer)
	 ("C->" mc/mark-next-like-this)
	 ("C-M-<" mc/mark-all-like-this)
	 ("C-M-SPC" set-rectangular-region-anchor)
	 ("C-x o" switch-window)
	 ("C-x C-f" helm-for-files)
	 ("C-x f" find-file)
	 ("C-x G" magit-status)))
(define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
(define-key helm-map (kbd "C-z") 'helm-select-action)
