(global-set-key (kbd "<f1>") 'man)
(global-set-key (kbd "<f5>") 'revert-buffer)
(global-set-key (kbd "C-S-RET") 'org-insert-subheading)
(global-set-key (kbd "C-S-S") 'tags-search)
(global-set-key (kbd "C-x <f5>") 'revert-buffer)
(global-set-key (kbd "C-x C-o") 'speedbar-get-focus)
(global-set-key (kbd "C-x M-SPC") 'delete-blank-lines)
(global-set-key (kbd "M-g") 'goto-line)
(global-set-key (kbd "C-x w w") 'hilight-thing-at-point)
(global-set-key (kbd "C-c C-f") 'compile)
(global-set-key (kbd "C-c v") 'vc-compare-with-recent-version)
(global-set-key (kbd "C-c j") 'json-format)
